[package]
name = "switchboard-proto"
version = "0.1.0"
edition = "2021"

[dependencies]
futures-channel = "0.3.31"
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"
webrtc = "0.12.0"
